### ISSUE TITLE
請問一下程式碼的問題

### ISSUE THREAD

**Issue by NiOmmmm** [powerwolf543/DrawPokemonBallView#1]
你的程式碼好漂亮易懂,
想問一下在 drawRect 畫寶貝球, 有什麼情況下 layoutSubviews 也需要在劃一次呢?

innerBlackCircleLayer.fillColor = UIColor.whiteColor().CGColor
innerBlackCircleLayer.strokeColor = UIColor.blackColor().CGColor
innerBlackCircleLayer.lineWidth = 10.0
這樣畫 innerBlackCircleLayer 就可以取代 innerWhiteCirclePath

**Comment by powerwolf543** [comment]
@NiOmmmm 這樣View大小有變化的時候，透過重繪Layer，也會跟著一起變化。innerBlackCircleLayer的確這樣做就可以了。

**Comment by NiOmmmm** [comment]
謝謝 !!
